### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by tfarina223** [danimahardhika/candybar-sample#7]
Hello, I'm new to this so maybe I just messed something up. I'm trying to do the setup tutorial with the sample project but I keep getting an error in build.gradle, "Failed to resolve: com.github.KeepSafe:TapTargetView:-SNAPSHOT"

Also, when I go to change "import com.material.dashboard.candybar.sample.R;" I'm only changing 1 from what I can see in preview and I get a bunch of errors pop up, mostly in MuzeiService.java, not sure if I should worry about that.

Thank you!

**Comment by danimahardhika** [comment]
https://github.com/danimahardhika/candybar-library/issues/91 Just update to latest release
